services:
  - type: web
    plan: free
    name: File-Sharing-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/TeamTMZ/File-Sharing-Bot.git      
    branch: main
    envVars:
      - key: TG_BOT_TOKEN 
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMINS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URI
        sync: false 
      - key: PORT
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
      - key: TG_BOT_WORKERS
        sync: false
    autoDeploy: true
